### ISSUE TITLE
Removing escape bindings does not work as expected

### ISSUE THREAD

**Issue by thicileares** [softmoth/zsh-vim-mode#27]
Hi, I am trying to remove all bindings starting with `<esc>`, like you suggest for getting rid of the delay for entering normal mode. However, I can copy-paste from the site you linked
```
bindkey -rpM viins '\e'
```
and the delay when pressing literally pressing `^[` (my preferred way), or pressing the `<esc>` key, is still there. However, when I press the left arrow key, for example, I am instantly put into normal mode, and my last two characters are deleted. I also tried
```
bindkey -rpM viins '^[^['
```
and this also did not remove the delay, even when pressing escape twice, but when I press `<alt>+arrow`, I am put into normal mode, at the beginning of the word. 

I am running zsh 5.8.

**Comment by softmoth** [comment]
Thank you for reporting this. I'll try to reproduce and see what is happening.

**Comment by softmoth** [comment]
When I remove **all** escape-prefixed bindings with `bindkey -rpM viins '\e'`, it does work well. As soon as I hit `^[` (or `<Escape>`) one time, it moves me into Normal mode.

The order of the options does matter here, in that you do **not** want to do `bindkey -p '\e' -r`. That will simply bind `^[` to an unrecognized `-r` instead of `vi-cmd-mode`.

Hitting the left arrow (depending on your terminal) will send `^[[D`, which may explain why you're losing characters at the end. I suspect that hitting the down arrow will move you into Normal mode and back a Word instead, since it sends `^[[B`.

You can verify that all the escape-prefixed bindings are gone, by running `bindkey -p '\e'`. You should see zero rows printed. Running `bindkey | fgrep '^['` should show the single binding for `vi-cmd-mode` that you'll get with `bindkey '\e'`.

I did find a bug with hitting `<Escape>` twice in a row, and have opened that as issue #28. But this one I can't reproduce. Please try a simple .zshrc like this:

```
source ~/path/to/zsh-vim-mode/zsh-vim-mode.plugin.zsh
bindkey -r -p '^['
bindkey -p '^['
bindkey | fgrep '^['
```
When you create a new shell, that should show a single binding for `vi-cmd-mode` above the prompt. Hitting `^[` should go to Normal mode with no delay. If it does, then you can gradually add back the other parts of your .zshrc to identify what is causing the issue.

**Comment by thicileares** [comment]
Thank you, turns out it was a few lines added automatically by compinstalll when setting zsh that was causing the problem. The delay is now gone! Thanks again!
