### ISSUE TITLE
Diff the "*" and "+" register

### ISSUE THREAD

**Issue by kuang22** [softmoth/zsh-vim-mode#36]
When using shell based on X11 (like in Ubuntu20.04), there are two registers "*" and "+" which actually could store different contents in vim, but in zsh-vim-mode, the contents in "*" and "+" registers seem both in "+".

I don't understand why. 
To briefly explain, I will give an example. when I use the mouse to select something in the terminal, the contents are stored in the "*" register( For example "Picture").
Then I open vim and select something and paste them with the "+" register(For example "temp").
Now, if I will get "temp" with "+p and "Picture" with "*p in vim which is reasonable.
However, if I go back to the terminal (quit vim), and use Esc to enter zsh-vim-mode, then I will get "temp" whether with "+p or "*p. That's the problem.
It seems like I couldn't use "*" register in zsh-vim-mode.

Is that because I didn't config zsh-vim-mode correctly or just the plugin lack the support for "*" register?
Hopefully, you can help me. Thx in advance.

**Comment by softmoth** [comment]
There is no support in `zsh-vim-mode` for copy and paste; any copy and paste behavior is being handled by your terminal application or possibly some other ZSH feature or plugin.

##  Proposed solutions

### Use the paste feature of your terminal application

Most terminals will include key bindings to paste into the terminal. Probably most common is `Shift+Ctrl+V`, and usually it can be configured from a menu or configuration file for the terminal application. You can probably also choose whether it uses the PRIMARY or CLIPBOARD selection buffer.

### Use a separate ZSH plugin

You might get the behavior you want from this plugin: https://github.com/kutsan/zsh-system-clipboard . I have not reviewed that plugin or tried it, I just found it via Google!

### Use a terminal multiplexer (tmux or screen)

Terminal multiplexer programs like tmux and screen provide yet another separate clipboard. It is possible to define key bindings so that copying/pasting in tmux updates the X server's CLIPBOARD and vice versa.

### Roll your own solution with `xsel`, `bindkey`, etc.

If you want to understand what is happening with your X server selections, you could install the `xsel` program to examine the contents of the different selection buffers. This description comes from the `xsel`(1x) man page:

> The  X  server maintains three selections, called PRIMARY, SECONDARY and CLIPBOARD. The PRIMARY selection is conventionally used to implement copying and pasting via the middle mouse button. The SECONDARY and CLIPBOARD selections are less frequently used by application programs.

Using `xsel -o -p`, `xsel -o -s`, and `xsel -o -b` will display the contents of PRIMARY, SECONDARY, and CLIPBOARD respectively:

```echo "primary: '$(xsel -o -p)'"; echo "secondary: '$(xsel -o -s)'"; echo "clipboard: '$(xsel -o -b)'";```

The 'put' function in ZSH's vi line editor does not use any of those X selection buffers. It has its own buffer which is set when you use `backward-kill-line` (^U), `vi-delete` (d), `vi-yank` (y), etc., and is read when you use `vi-put-after` (p), etc. You could create new bindings which replace these operations. Probably it is a lot easier to find an existing plugin which already does this.
